version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    executor: node/default 
    steps: 
      - run: git clone https://github.com/pnpm/pnpm.git && cd pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run: curl https://raw.githubusercontent.com/flightpkg/ci/main/flightjs/build.sh | sh
  rebrand:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: curl https://raw.githubusercontent.com/flightpkg/ci/main/flightjs/rebranding.sh | sh
      - run: git add -A
      - run: 'git commit -m chore(ci): apply flightjs branding" --no-verify'
      - run: git push --set-upstream https://github.com/flightpkg/javascript.git main --force

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build
      